pub mod video_feed;
pub mod camera_controls;
pub mod model_selector;
pub mod tolerance_slider;
pub mod tag_manager;
pub mod night_vision;
pub mod color_correction;
pub mod detection_overlay;
pub mod recording_indicator;
pub mod metrics_panel;

pub use video_feed::VideoFeed;
pub use camera_controls::CameraControls;
pub use model_selector::{ModelSelector, ModelInfo};
pub use tolerance_slider::ToleranceControls;
pub use tag_manager::{TagManager, Tag};
pub use night_vision::NightVisionControls;
pub use color_correction::ColorCorrection;
pub use detection_overlay::{DetectionOverlay, DetectionBox};
pub use recording_indicator::RecordingIndicator;
pub use metrics_panel::MetricsPanel;
